### ISSUE TITLE
[Question] Does it work with headphones, too?

### ISSUE THREAD

**Issue by galantra** [Brad331/DynamiQ#3]
Great project :)  

When I use high-impedance, I usually reach the gain level where clipping starts. The area that I boost most with EQ is bass.

**Comment by Brad331** [comment]
Yes, you could use it with headphones, but DynamiQ has enough impact to sound fidelity that you're better off using lower-impedance headphones or a cheap external DAC+amp instead.

**Comment by galantra** [comment]
Thanks for your answer. I noticed that my monitor has enough power to drive the 250 Ohm Beyerdynamics. So I ended up using that rather than plugging them directly into the computer.
